/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * 
 *
 * @author x14470572
 */
public class ChemGlossary extends javax.swing.JFrame {

    private String Term;
    private String Explanation;
    private String Category;
    
    private ArrayList <GlossaryOb> aList;
    private int count;
    /**
     * Creates new form Glossary
     */
    public ChemGlossary() {
        initComponents();
        Term = new String();
        Explanation = new String();
        Category = new String();
        aList = new ArrayList <>();
        count = 0;
    }

    
    private void writeObjectToFile(){
        try{
            File f = new File("output.txt");
            FileOutputStream fow = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fow);
            
            oos.writeObject(aList);
            
            fow.close();
            oos.close();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
     private void readObjectFromFile(){
        try{
            File f = new File("output.txt");
            FileInputStream fis = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(fis);
            
            ArrayList<GlossaryOb> arr = new ArrayList<>();
            
            arr = (ArrayList<GlossaryOb>) ois.readObject();
            
            aList = arr;
            ois.close();
            fis.close();            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        TermLbl = new javax.swing.JLabel();
        TermTF = new javax.swing.JTextField();
        ExpLbl = new javax.swing.JLabel();
        ExpTF = new javax.swing.JTextField();
        CateLbl = new javax.swing.JLabel();
        CateTF = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        DisplayBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(0, 153, 204));
        TitleLbl.setText("Glossary");

        BackBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        TermLbl.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        TermLbl.setText("Term:");

        ExpLbl.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        ExpLbl.setText("Explanation:");

        CateLbl.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        CateLbl.setText("Category:");

        CateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CateTFActionPerformed(evt);
            }
        });

        AddBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        DelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DelBtn.setText("Delete");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        DisplayBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DisplayBtn.setText("Display All");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });

        SearchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CateLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(TermLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(ExpLbl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ExpTF, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(TermTF)
                            .addComponent(CateTF))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(DisplayBtn)
                .addGap(28, 28, 28)
                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TermLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TermTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ChemStudy().setVisible(true);
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void CateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CateTFActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
         String SearchType = JOptionPane.showInputDialog(null,"Enter Term: ");
        
        for(int i = 0; i < aList.size();i++){
            if(SearchType.equalsIgnoreCase(aList.get(i).getTerm())){
                 JOptionPane.showMessageDialog(null, "Term: "+aList.get(i).getTerm()+"\n Explanation: "+aList.get(i).getExplanation()+"\n Category: "+aList.get(i).getCategory());
            }
            else{
                 
            }
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        Term = TermTF.getText();
        Explanation = ExpTF.getText();
        Category = CateTF.getText();
        
        
        //create a new Assessment object
        GlossaryOb a = new GlossaryOb();
        
        //add contents of textfields to q
        a.setTerm(Term);
        a.setExplanation(Explanation);
        a.setCategory(Category);
        
        
        //add q to array of Assessment objects
        aList.add(a);
        //increase count to show that another object has been added to the array
        count++;
        
        TermTF.setText("");
        ExpTF.setText("");
        CateTF.setText("");
        
        writeObjectToFile();
        
    }//GEN-LAST:event_AddBtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < aList.size();i++){
             if(aList.size()>=0){
                 JOptionPane.showMessageDialog(null, "Term: "+aList.get(i).getTerm()+"\n Explanation: "+aList.get(i).getExplanation()+"\n Category: "+aList.get(i).getCategory());
            }
             else{
                 JOptionPane.showMessageDialog(null,"No entries found");
             } 
         }
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed
        // TODO add your handling code here:
        if(TermTF.getText().equals("")||ExpTF.getText().equals("")||CateTF.getText().equals("")){
            JOptionPane.showInputDialog(null, "Enter to delete");
        }
        else if(count == 0){
            JOptionPane.showMessageDialog(null, "Nothing to delete");
        }
        else{
             Term = TermTF.getText();
             Explanation = ExpTF.getText();
             Category = CateTF.getText();
            
        }
        
        for(int i = 0; i < aList.size();i++){
            if(aList.get(i).getTerm().equals(Term)&&aList.get(i).getExplanation().equals(Explanation)&&aList.get(i).getCategory().equals(Category)){
                aList.remove(i);
                count = count - 1;
                JOptionPane.showMessageDialog(null,"Item deleted at " +i);
                break;
            }
            if(i==count-1){
                JOptionPane.showMessageDialog(null, "Nothing to delete");
            }
        }
    }//GEN-LAST:event_DelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glossary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glossary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glossary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glossary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChemGlossary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel CateLbl;
    private javax.swing.JTextField CateTF;
    private javax.swing.JButton DelBtn;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JLabel ExpLbl;
    private javax.swing.JTextField ExpTF;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel TermLbl;
    private javax.swing.JTextField TermTF;
    private javax.swing.JLabel TitleLbl;
    // End of variables declaration//GEN-END:variables
}
