/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x14470572
 */
public class ChemQuiz extends javax.swing.JFrame {

    private ArrayList <String> answers;
    private ArrayList <String> questions;
    private int count;
    private int answered;
    private int correct;
    private int wrong;
    
    /**
     * Creates new form ChemQuiz
     */
    public ChemQuiz() {
        initComponents();
        
        answers = new ArrayList<String>();  
        questions = new ArrayList<String>();

        String q1 = "If an acid is spilt on the laboratory bench, what substance should be added to it in order to neutralise it?";
        String q2 = "According to the Bronsted-Lowry Theory an acid breaks up into?";
        String q3 = "An acid dissociates in water to produce hydrogen ions was first proposed by which chemist?";
        String q4 = "What type of metal is used as a shield against radioactive emissions?";
        String q5 = "Radioactivity may be detected by which one of the following instruments?";
        String q6 = "Alpha, beta and gamma radiations have different penetrating powers. Put them in increasing order of penetration?";
        String q7 = "The Particulate Nature of Matter means that all matter is composed of?";
        String q8 = "In industry, the heat of combustion of a substance may be measured using?";
        String q9 = "TRUE or FALSE? An exothermic reaction is one where heat is released ?";
        String q10 = "The law which states that \"Energy cannot be created nor destroyed, but may be converted from one form to another\" is known as?";
        
        String a1 = "Chalk";
        String a2 = "a conjugate base and a proton";
        String a3 = "Svente Arrhenius";
        String a4 = "Lead";
        String a5 = "Geiger-Muller tube";
        String a6 = "Alpha, beta, gamma";
        String a7 = "small particles";
        String a8 = "bomb calorimeter";
        String a9 = "TRUE";
        String a10 = "Law of conservation of energy";
        
        questions.add(q1);
        questions.add(q2);
        questions.add(q3); 
        questions.add(q4); 
        questions.add(q5);
        questions.add(q6); 
        questions.add(q7); 
        questions.add(q8); 
        questions.add(q9); 
        questions.add(q10); 
        
        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        
        count = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatsBtn = new javax.swing.JButton();
        SubjectL = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        ActQuizBtn = new javax.swing.JButton();
        HigherL = new javax.swing.JLabel();
        AnsweredLbl = new javax.swing.JLabel();
        CorrectLbl = new javax.swing.JLabel();
        WrongLbl = new javax.swing.JLabel();
        ALbl = new javax.swing.JLabel();
        CLbl = new javax.swing.JLabel();
        WLbl = new javax.swing.JLabel();

        StatsBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        StatsBtn.setText("Statistics");
        StatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatsBtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubjectL.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        SubjectL.setForeground(new java.awt.Color(0, 153, 204));
        SubjectL.setText("Chemistry");

        BackBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        ActQuizBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        ActQuizBtn.setText("Take Quiz");
        ActQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActQuizBtnActionPerformed(evt);
            }
        });

        HigherL.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        HigherL.setForeground(new java.awt.Color(0, 153, 255));
        HigherL.setText("Higher");

        AnsweredLbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        AnsweredLbl.setText("Questions Answered:");

        CorrectLbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        CorrectLbl.setText("Questions Correct:");

        WrongLbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        WrongLbl.setText("Questions Wrong:");

        ALbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N

        CLbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N

        WLbl.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HigherL, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubjectL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ActQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AnsweredLbl)
                            .addComponent(CorrectLbl)
                            .addComponent(WrongLbl))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ALbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(WLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(SubjectL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(ActQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnsweredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CorrectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WrongLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(WLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HigherL, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ChemMain().setVisible(true);
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ActQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActQuizBtnActionPerformed
        // TODO add your handling code here:
         while(count < answers.size()){
           

            String inAnswer = JOptionPane.showInputDialog(null,questions.get(count));

            if(inAnswer.equals(answers.get(count))){
                JOptionPane.showMessageDialog(null,"Correct");
                answered = answered +1;
                correct = correct +1;
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Incorrect");
                answered = answered +1;
                wrong = wrong +1;
            }
            count++;
        }
         
        ALbl.setText(""+answers.size());
        CLbl.setText(""+correct);
        WLbl.setText(""+wrong);
              
        
        
        
         
        
    }//GEN-LAST:event_ActQuizBtnActionPerformed

    private void StatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatsBtnActionPerformed
        // TODO add your handling code her
        
        
    }//GEN-LAST:event_StatsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChemQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChemQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChemQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChemQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChemQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALbl;
    private javax.swing.JButton ActQuizBtn;
    private javax.swing.JLabel AnsweredLbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel CLbl;
    private javax.swing.JLabel CorrectLbl;
    private javax.swing.JLabel HigherL;
    private javax.swing.JButton StatsBtn;
    private javax.swing.JLabel SubjectL;
    private javax.swing.JLabel WLbl;
    private javax.swing.JLabel WrongLbl;
    // End of variables declaration//GEN-END:variables
}
