/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author Mark Hayden
 */
public class Exams extends javax.swing.JFrame {

    /**
     * Creates new form Exams
     */
    public Exams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        Examsbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        Studybtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 287));

        lblWelcome.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 153, 255));
        lblWelcome.setText("Exam Timetable");

        Examsbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Examsbtn.setText("Exam Timetable");
        Examsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamsbtnActionPerformed(evt);
            }
        });

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Studybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Studybtn.setText("Study Planner");
        Studybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backbtn)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Studybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Examsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(lblWelcome))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Backbtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblWelcome)))
                .addGap(18, 18, 18)
                .addComponent(Examsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Studybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new JCMain().setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void ExamsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamsbtnActionPerformed
        // TODO add your handling code here:
        
        //Call java classes
        Info in;
        Exam ex;
        //Declare 3 Info objects
        Info e1,e2,e3;
        
        //Construct e1 as 3 instances of Exams
        e1 = new Exam("Physics",930,1130,"Monday","Gym");
        e2 = new Exam("Biology",1200,1400,"Thursday","Theatre");
        e3 = new Exam("Chemistry",1400,1600,"Thursday","Main Hall");
        
        //if e1 is an instance of Exams, change Center variabe and print
        if(e1 instanceof Exam){
            Exam e = (Exam) e1;
            JOptionPane.showMessageDialog(null, e.getDetails());
            
            JOptionPane.showMessageDialog(null,"Alert, location change");
            e.setLocation("Main Hall");
            JOptionPane.showMessageDialog(null, e.getDetails());
        }
        
        //if e1 is an instance of Exams, change Center variabe and print
        if(e2 instanceof Exam){
            Exam e = (Exam) e2;
            JOptionPane.showMessageDialog(null, e.getDetails());
            
            JOptionPane.showMessageDialog(null,"Alert, day and time change");
            e.setDay("Friday");
            e.setTimestart(1230);
            e.setTimefin(1430);
            JOptionPane.showMessageDialog(null, e.getDetails());
        }
        
        //if e1 is an instance of Exams, change Center variabe and print
        if(e3 instanceof Exam){
            Exam e = (Exam) e3;
            JOptionPane.showMessageDialog(null, e.getDetails());
        }
        
        
    }//GEN-LAST:event_ExamsbtnActionPerformed

    private void StudybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudybtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StudyPlanGUI().setVisible(true);
    }//GEN-LAST:event_StudybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Examsbtn;
    private javax.swing.JButton Studybtn;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
