/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author x14470572
 */
public class PastPapers extends javax.swing.JFrame {

    /**
     * Creates new form PastPapers
     */
    public PastPapers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubjectL = new javax.swing.JLabel();
        Title1L = new javax.swing.JLabel();
        Title2L = new javax.swing.JLabel();
        LevelL = new javax.swing.JLabel();
        EP2014Btn = new javax.swing.JButton();
        EP2013Btn = new javax.swing.JButton();
        EP2012Btn = new javax.swing.JButton();
        MS2014Btn = new javax.swing.JButton();
        EP2011Btn = new javax.swing.JButton();
        MS2013Btn = new javax.swing.JButton();
        MS2012Btn = new javax.swing.JButton();
        MS2011Btn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubjectL.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        SubjectL.setForeground(new java.awt.Color(0, 153, 255));
        SubjectL.setText("Chemistry");

        Title1L.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        Title1L.setText("Exam Papers");

        Title2L.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        Title2L.setText("Marking Schemes");

        LevelL.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        LevelL.setForeground(new java.awt.Color(0, 153, 204));
        LevelL.setText("Higher");

        EP2014Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EP2014Btn.setText("2014");
        EP2014Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EP2014BtnActionPerformed(evt);
            }
        });

        EP2013Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EP2013Btn.setText("2013");
        EP2013Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EP2013BtnActionPerformed(evt);
            }
        });

        EP2012Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EP2012Btn.setText("2012");
        EP2012Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EP2012BtnActionPerformed(evt);
            }
        });

        MS2014Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MS2014Btn.setText("2014");
        MS2014Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS2014BtnActionPerformed(evt);
            }
        });

        EP2011Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EP2011Btn.setText("2011");
        EP2011Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EP2011BtnActionPerformed(evt);
            }
        });

        MS2013Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MS2013Btn.setText("2013");
        MS2013Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS2013BtnActionPerformed(evt);
            }
        });

        MS2012Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MS2012Btn.setText("2012");
        MS2012Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS2012BtnActionPerformed(evt);
            }
        });

        MS2011Btn.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        MS2011Btn.setText("2011");
        MS2011Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS2011BtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EP2014Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title1L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EP2013Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EP2012Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EP2011Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title2L, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MS2014Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MS2013Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MS2012Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MS2011Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(SubjectL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LevelL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubjectL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title2L, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title1L, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EP2014Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MS2014Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MS2013Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EP2013Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MS2012Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EP2012Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MS2011Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EP2011Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(LevelL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ChemStudy().setVisible(true);
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void EP2014BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EP2014BtnActionPerformed
        // TODO add your handling code here:
        try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/exampapers/2014/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    
    }//GEN-LAST:event_EP2014BtnActionPerformed

    private void EP2013BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EP2013BtnActionPerformed
        // TODO add your handling code here:
          try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/exampapers/2013/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_EP2013BtnActionPerformed

    private void EP2012BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EP2012BtnActionPerformed
        // TODO add your handling code here:
          try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/exampapers/2012/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_EP2012BtnActionPerformed

    private void EP2011BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EP2011BtnActionPerformed
        // TODO add your handling code here:
           try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/exampapers/2011/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_EP2011BtnActionPerformed

    private void MS2014BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS2014BtnActionPerformed
        // TODO add your handling code here:
           try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2014/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_MS2014BtnActionPerformed

    private void MS2013BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS2013BtnActionPerformed
        // TODO add your handling code here:
           try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2013/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_MS2013BtnActionPerformed

    private void MS2012BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS2012BtnActionPerformed
        // TODO add your handling code here:
           try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2012/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_MS2012BtnActionPerformed

    private void MS2011BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS2011BtnActionPerformed
        // TODO add your handling code here:
           try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2011/LC022ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_MS2011BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PastPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PastPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PastPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PastPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PastPapers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton EP2011Btn;
    private javax.swing.JButton EP2012Btn;
    private javax.swing.JButton EP2013Btn;
    private javax.swing.JButton EP2014Btn;
    private javax.swing.JLabel LevelL;
    private javax.swing.JButton MS2011Btn;
    private javax.swing.JButton MS2012Btn;
    private javax.swing.JButton MS2013Btn;
    private javax.swing.JButton MS2014Btn;
    private javax.swing.JLabel SubjectL;
    private javax.swing.JLabel Title1L;
    private javax.swing.JLabel Title2L;
    // End of variables declaration//GEN-END:variables
}
