/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x14111021
 */
public class PhysicsStuPlanOl extends javax.swing.JFrame {

    /**
     * Creates new form PhysicsStu
     */
    
    private ArrayList <StudyPlan_1> stuPlan;
    private String day, subject, note;
    private double duration, time;
    private int count;
    
    public PhysicsStuPlanOl() {
        initComponents();
        stuPlan = new ArrayList <>();
        day = new String();
        note = new String();
        subject = new String();
        duration = 0.0;
        time = 0.0;
        count = 1;
        
        
    }
    
    private void writeObjectToFile(){
        
            try{
                File f = new File("stu_plan.txt");
                FileOutputStream fOS = new FileOutputStream(f);
                ObjectOutputStream oOS = new ObjectOutputStream(fOS);
            
                oOS.writeObject(stuPlan);
            
                fOS.close();
                oOS.close();
            
            }
        
            catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            
        
        
        }
    
    private void readObjectFromFile(){
        
        try{
            File f = new File("stu_plan.txt");
            FileInputStream fIS = new FileInputStream(f);
            ObjectInputStream oIS = new ObjectInputStream(fIS);
            
            ArrayList<StudyPlan_1> arr = new ArrayList<>();
            
            arr = (ArrayList<StudyPlan_1>) oIS.readObject();
            
            stuPlan = arr;
            oIS.close();
            fIS.close();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        physLbl = new javax.swing.JLabel();
        studyLbl = new javax.swing.JLabel();
        dayLbl = new javax.swing.JLabel();
        lcLbl = new javax.swing.JLabel();
        subjectLbl = new javax.swing.JLabel();
        backBtnOL = new javax.swing.JButton();
        dayTF = new javax.swing.JTextField();
        durationLbl = new javax.swing.JLabel();
        durationTF = new javax.swing.JTextField();
        timeLbl = new javax.swing.JLabel();
        timeTF = new javax.swing.JTextField();
        subjectTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtnHL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        physLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        physLbl.setText("Physics");

        studyLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studyLbl.setText("Study");

        dayLbl.setText("What day or note is this plan for?**");

        lcLbl.setText("L.C.");

        subjectLbl.setText("What subject would you like to study?*");

        backBtnOL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtnOL.setText("Back O.L.");
        backBtnOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnOLActionPerformed(evt);
            }
        });

        dayTF.setText("Day/Note");
        dayTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTFActionPerformed(evt);
            }
        });

        durationLbl.setText("How long would you like to study?*");

        durationTF.setText("Duration");
        durationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTFActionPerformed(evt);
            }
        });

        timeLbl.setText("What time would you like to study?*");

        timeTF.setText("Time");

        subjectTF.setText("Subject");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("*All fields must be filled");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("** Please enter the full name");

        backBtnHL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtnHL.setText("Back H.L.");
        backBtnHL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnHLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcLbl)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(subjectLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(durationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(studyLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(physLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backBtnOL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backBtnHL))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(physLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studyLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dayLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durationLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtnHL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtnOL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lcLbl)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnOLActionPerformed
        this.dispose();
        new PhysicsStuLCOL().setVisible(true);
    }//GEN-LAST:event_backBtnOLActionPerformed

    private void durationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTFActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        
        if(day.equalsIgnoreCase("monday")||day.equalsIgnoreCase("tuesday")||day.equalsIgnoreCase("wednesday")||day.equalsIgnoreCase("thursday")||day.equalsIgnoreCase("friday")||day.equalsIgnoreCase("saturday")||day.equalsIgnoreCase("sunday")){
            
            day = dayTF.getText();
            
        }
        else{
            
            note = dayTF.getText();
            
        }
        
        
        subject = subjectTF.getText();
        time = Double.parseDouble(timeTF.getText());
        duration = Double.parseDouble(durationTF.getText());
        
        StudyPlan_1 stuP = new StudyPlan_1();
        NotePlan noteP = new NotePlan(day,subject,time,duration,note);
        
        if(day.equalsIgnoreCase("monday")||day.equalsIgnoreCase("tuesday")||day.equalsIgnoreCase("wednesday")||day.equalsIgnoreCase("thursday")||day.equalsIgnoreCase("friday")||day.equalsIgnoreCase("saturday")||day.equalsIgnoreCase("sunday")){
            
            stuP.setDay(day); 
            
        }
        
        else{
            
            noteP.setNote(note); 
  
        }
        
        stuP.setSubject(subject);
        stuP.setTime(time);
        stuP.setDuration(duration);
        
        stuPlan.add(stuP);
        
        JOptionPane.showMessageDialog(null, "Your plan has been added.");
        
        count++;
        
        dayTF.setText("");
        subjectTF.setText("");
        timeTF.setText("");
        durationTF.setText("");
        
        writeObjectToFile();
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        
        readObjectFromFile();
        
        for(int i = 0; i < stuPlan.size(); i++){
            
            if(stuPlan.size()>0){
            
                JOptionPane.showMessageDialog(null, "Day/Note: " + stuPlan.get(i).getDay() + "\nSubject: " + stuPlan.get(i).getSubject() + "\nTime: " + stuPlan.get(i).getTime() + "\nDuration: " + stuPlan.get(i).getDuration());
                
            }
            else{
                    
                JOptionPane.showMessageDialog(null, "No plans found");
                    
            }
            
        }
        
    }//GEN-LAST:event_displayBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(dayTF.getText().equals("")||subjectTF.getText().equals("")||durationTF.getText().equals("")||timeTF.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Please enter Day, Duration, Time and Subject to delete");
            
        }
        else if(count==0){
            
            JOptionPane.showMessageDialog(null, "Sorry, there no items to delete");
            
        }
        else{
            if(day.equalsIgnoreCase("monday")||day.equalsIgnoreCase("tuesday")||day.equalsIgnoreCase("wednesday")||day.equalsIgnoreCase("thursday")||day.equalsIgnoreCase("friday")||day.equalsIgnoreCase("saturday")||day.equalsIgnoreCase("sunday")){
            
                day = dayTF.getText();
                
            }
            else{
                
                note = dayTF.getText();
                
            }
                duration = Double.parseDouble(durationTF.getText());
                time = Double.parseDouble(timeTF.getText());
                subject = subjectTF.getText();
         
         for(int i = 0; i < stuPlan.size(); i++){
         
            if(stuPlan.get(i).getDay().equalsIgnoreCase(day)||stuPlan.get(i).getDay().equalsIgnoreCase(note)&&stuPlan.get(i).getDuration()==duration&&stuPlan.get(i).getTime()==time&&stuPlan.get(i).getSubject().equalsIgnoreCase(subject)){
             
             stuPlan.remove(i);
             count = count - 1;
             JOptionPane.showMessageDialog(null, "Item deleted at " + i);
              break;
             
            }
            else if(count==0){
                    
                    JOptionPane.showMessageDialog(null, "There is nothing to delete");
                    
                    }
            
         }
            
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchType = JOptionPane.showInputDialog("Please enter the day you wish to search for: ");
        
        for(int i = 0; i<stuPlan.size(); i++){
            
            if(searchType.equalsIgnoreCase(stuPlan.get(i).getDay())){
            
               JOptionPane.showMessageDialog(null, "Day/Note: " + stuPlan.get(i).getDay() + "\nSubject: " + stuPlan.get(i).getSubject() + "\nTime: " + stuPlan.get(i).getTime() + "\nDuration: " + stuPlan.get(i).getDuration());
                
            }
            
            else{
                
                JOptionPane.showMessageDialog(null, "There is no item by that name to search");
                
            }
    }//GEN-LAST:event_searchBtnActionPerformed
    }
    private void dayTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTFActionPerformed

    private void backBtnHLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnHLActionPerformed
        
        this.dispose();
        new PhysicsStuLCHL().setVisible(true);
        
    }//GEN-LAST:event_backBtnHLActionPerformed

    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicsStuPlanOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicsStuPlanOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicsStuPlanOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicsStuPlanOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsStuPlanOl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtnHL;
    private javax.swing.JButton backBtnOL;
    private javax.swing.JLabel dayLbl;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel durationLbl;
    private javax.swing.JTextField durationTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lcLbl;
    private javax.swing.JLabel physLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel studyLbl;
    private javax.swing.JLabel subjectLbl;
    private javax.swing.JTextField subjectTF;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField timeTF;
    // End of variables declaration//GEN-END:variables
}
