/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

/**
 *
 * @author x14111021
 */
public class PhysicsAssLCHL extends javax.swing.JFrame {

    /**
     * Creates new form PhysicsAss
     */
    public PhysicsAssLCHL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupT1 = new javax.swing.ButtonGroup();
        buttonGroupT2 = new javax.swing.ButtonGroup();
        buttonGroupT3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        physLbl = new javax.swing.JLabel();
        assLbl = new javax.swing.JLabel();
        lcLbl = new javax.swing.JLabel();
        introLbl = new javax.swing.JLabel();
        gaugeLbl1 = new javax.swing.JLabel();
        gaugeLbl2 = new javax.swing.JLabel();
        gaugeLbl3 = new javax.swing.JLabel();
        gaugeLbl4 = new javax.swing.JLabel();
        gaugeLbl5 = new javax.swing.JLabel();
        topicLbl1 = new javax.swing.JLabel();
        t1radioBtn1 = new javax.swing.JRadioButton();
        t1RadioBtn2 = new javax.swing.JRadioButton();
        t1RadioBtn3 = new javax.swing.JRadioButton();
        t1RadioBtn4 = new javax.swing.JRadioButton();
        t1RadioBtn5 = new javax.swing.JRadioButton();
        topicLabel2 = new javax.swing.JLabel();
        gaugeLbl12345 = new javax.swing.JLabel();
        topicLbl3 = new javax.swing.JLabel();
        t2RadioBtn2 = new javax.swing.JRadioButton();
        t2RadioBtn3 = new javax.swing.JRadioButton();
        t2RadioBtn4 = new javax.swing.JRadioButton();
        t2RadioBtn5 = new javax.swing.JRadioButton();
        t2RadioBtn1 = new javax.swing.JRadioButton();
        t3RadioBtn2 = new javax.swing.JRadioButton();
        t3RadioBtn1 = new javax.swing.JRadioButton();
        t3RadioBtn4 = new javax.swing.JRadioButton();
        t3RadioBtn3 = new javax.swing.JRadioButton();
        t3RadioBtn5 = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        topicsLbl = new javax.swing.JLabel();
        hlLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        physLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        physLbl.setText("Physics");

        assLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        assLbl.setText("Assessment");

        lcLbl.setText("L.C.");

        introLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        introLbl.setText("This short questionaire will gauge your ability");

        gaugeLbl1.setText("1 - Not Confident At All");

        gaugeLbl2.setText("2 - Somewhat Confident");

        gaugeLbl3.setText("3 - Ok But More Work");

        gaugeLbl4.setText("4 - Confident");

        gaugeLbl5.setText("5 - Completely Confident");

        topicLbl1.setText("Scientific Notation:");

        buttonGroupT1.add(t1radioBtn1);
        t1radioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1radioBtn1ActionPerformed(evt);
            }
        });

        buttonGroupT1.add(t1RadioBtn2);
        t1RadioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1RadioBtn2ActionPerformed(evt);
            }
        });

        buttonGroupT1.add(t1RadioBtn3);
        t1RadioBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1RadioBtn3ActionPerformed(evt);
            }
        });

        buttonGroupT1.add(t1RadioBtn4);

        buttonGroupT1.add(t1RadioBtn5);

        topicLabel2.setText("Equations:");

        gaugeLbl12345.setText("  1      2      3     4      5");

        topicLbl3.setText("Plane & Sperical Mirrors:");

        buttonGroupT2.add(t2RadioBtn2);
        t2RadioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2RadioBtn2ActionPerformed(evt);
            }
        });

        buttonGroupT2.add(t2RadioBtn3);
        t2RadioBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2RadioBtn3ActionPerformed(evt);
            }
        });

        buttonGroupT2.add(t2RadioBtn4);

        buttonGroupT2.add(t2RadioBtn5);

        buttonGroupT2.add(t2RadioBtn1);
        t2RadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2RadioBtn1ActionPerformed(evt);
            }
        });

        buttonGroupT3.add(t3RadioBtn2);
        t3RadioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3RadioBtn2ActionPerformed(evt);
            }
        });

        buttonGroupT3.add(t3RadioBtn1);
        t3RadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3RadioBtn1ActionPerformed(evt);
            }
        });

        buttonGroupT3.add(t3RadioBtn4);

        buttonGroupT3.add(t3RadioBtn3);
        t3RadioBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3RadioBtn3ActionPerformed(evt);
            }
        });

        buttonGroupT3.add(t3RadioBtn5);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextBtn.setText("Next");

        topicsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topicsLbl.setText("Topics");

        hlLbl.setText("H.L.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topicLabel2)
                            .addComponent(topicLbl3)
                            .addComponent(topicsLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(topicLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(t1radioBtn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t1RadioBtn2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t1RadioBtn3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t1RadioBtn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t1RadioBtn5))
                                .addComponent(gaugeLbl12345, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(t2RadioBtn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t2RadioBtn2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t2RadioBtn3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t2RadioBtn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t2RadioBtn5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(t3RadioBtn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t3RadioBtn2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t3RadioBtn3)
                                    .addGap(4, 4, 4)
                                    .addComponent(t3RadioBtn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t3RadioBtn5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lcLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hlLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(assLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(physLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(introLbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gaugeLbl1)
                                            .addComponent(gaugeLbl3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gaugeLbl4)
                                            .addComponent(gaugeLbl2)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(gaugeLbl5)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(physLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(assLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(introLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gaugeLbl1)
                            .addComponent(gaugeLbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gaugeLbl3)
                                    .addComponent(gaugeLbl4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gaugeLbl5)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(topicsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(topicLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addComponent(topicLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(topicLbl3))
                            .addComponent(t3RadioBtn5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gaugeLbl12345)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1RadioBtn3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1RadioBtn2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1RadioBtn4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1radioBtn1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1RadioBtn5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2RadioBtn3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t2RadioBtn2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t2RadioBtn4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t2RadioBtn1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t2RadioBtn5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t3RadioBtn3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t3RadioBtn2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t3RadioBtn4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t3RadioBtn1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcLbl)
                    .addComponent(hlLbl))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1radioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1radioBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1radioBtn1ActionPerformed

    private void t1RadioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1RadioBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1RadioBtn2ActionPerformed

    private void t1RadioBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1RadioBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1RadioBtn3ActionPerformed

    private void t2RadioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2RadioBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2RadioBtn2ActionPerformed

    private void t2RadioBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2RadioBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2RadioBtn3ActionPerformed

    private void t2RadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2RadioBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2RadioBtn1ActionPerformed

    private void t3RadioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3RadioBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3RadioBtn2ActionPerformed

    private void t3RadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3RadioBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3RadioBtn1ActionPerformed

    private void t3RadioBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3RadioBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3RadioBtn3ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new PhysicsLcHl().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicsAssLCHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicsAssLCHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicsAssLCHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicsAssLCHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsAssLCHL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroupT1;
    private javax.swing.ButtonGroup buttonGroupT2;
    private javax.swing.ButtonGroup buttonGroupT3;
    private javax.swing.JLabel gaugeLbl1;
    private javax.swing.JLabel gaugeLbl12345;
    private javax.swing.JLabel gaugeLbl2;
    private javax.swing.JLabel gaugeLbl3;
    private javax.swing.JLabel gaugeLbl4;
    private javax.swing.JLabel gaugeLbl5;
    private javax.swing.JLabel hlLbl;
    private javax.swing.JLabel introLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lcLbl;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel physLbl;
    private javax.swing.JRadioButton t1RadioBtn2;
    private javax.swing.JRadioButton t1RadioBtn3;
    private javax.swing.JRadioButton t1RadioBtn4;
    private javax.swing.JRadioButton t1RadioBtn5;
    private javax.swing.JRadioButton t1radioBtn1;
    private javax.swing.JRadioButton t2RadioBtn1;
    private javax.swing.JRadioButton t2RadioBtn2;
    private javax.swing.JRadioButton t2RadioBtn3;
    private javax.swing.JRadioButton t2RadioBtn4;
    private javax.swing.JRadioButton t2RadioBtn5;
    private javax.swing.JRadioButton t3RadioBtn1;
    private javax.swing.JRadioButton t3RadioBtn2;
    private javax.swing.JRadioButton t3RadioBtn3;
    private javax.swing.JRadioButton t3RadioBtn4;
    private javax.swing.JRadioButton t3RadioBtn5;
    private javax.swing.JLabel topicLabel2;
    private javax.swing.JLabel topicLbl1;
    private javax.swing.JLabel topicLbl3;
    private javax.swing.JLabel topicsLbl;
    // End of variables declaration//GEN-END:variables
}
