/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import java.io.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Mark Hayden
 */
public class StudyPlanGUI extends javax.swing.JFrame {
    private String name;
    private String day;
    private int starttime;
    private int fintime;
    
    private ArrayList <StudyPlan> aList;
    private int count;

    /**
     * Creates new form StudyPlanGUI
     */
    public StudyPlanGUI() {
        initComponents();
        name = new String();
        day = new String();
        starttime = 0;
        fintime = 0;
        aList = new ArrayList <>();
        count = 0;
    }
    
    private void writeObjectToFile(){
        try{
            File f = new File("data.txt");
            FileOutputStream fow = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fow);
            
            oos.writeObject(aList);
            
            fow.close();
            oos.close();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    private void readObjectFromFile(){
        try{
            File f = new File("data.txt");
            FileInputStream fis = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(fis);
            
            ArrayList<StudyPlan> arr = new ArrayList<>();
            
            arr = (ArrayList<StudyPlan>) ois.readObject();
            
            aList = arr;
            ois.close();
            fis.close();            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblTimeStart = new javax.swing.JLabel();
        lblTimeFin = new javax.swing.JLabel();
        Nametf = new javax.swing.JTextField();
        Studytf = new javax.swing.JTextField();
        Starttf = new javax.swing.JTextField();
        Finishtf = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblEx1 = new javax.swing.JLabel();
        lblEx2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 153, 255));
        lblWelcome.setText("Welcome to your Study Planner");

        lblSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubject.setText("Subject Name:");

        lblDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDay.setText("Day of Study:");

        lblTimeStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTimeStart.setText("Time to Start:");

        lblTimeFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTimeFin.setText("Time to Finish:");

        Studytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudytfActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display All");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEx1.setText("e.g. 1123");

        lblEx2.setText("e.g. 1234");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTimeFin)
                                            .addGap(54, 54, 54)
                                            .addComponent(Finishtf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDay)
                                                .addComponent(lblSubject))
                                            .addGap(52, 52, 52)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Studytf)
                                                .addComponent(Nametf))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEx2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTimeStart)
                                    .addGap(58, 58, 58)
                                    .addComponent(Starttf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEx1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSearch)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDisplay)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDelete)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(lblWelcome))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(Nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDay)
                    .addComponent(Studytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeStart)
                    .addComponent(Starttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEx1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeFin)
                    .addComponent(Finishtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEx2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudytfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudytfActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        readObjectFromFile();
         for (int i = 0; i < aList.size(); i++) {
            if (aList.size() >= 0) {
                JOptionPane.showMessageDialog(null, "Subject Name: " + aList.get(i).getName() + "\n Day of Study: " + aList.get(i).getDay() + "\n Time to Start: " + aList.get(i).getStarttime() + "\n Time to Finish: " + aList.get(i).getFintime());
            } else {
                JOptionPane.showMessageDialog(null, "No entries found");
            }
        }
             
         
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String SearchType = JOptionPane.showInputDialog(null,"Enter Day: ");
        
        for(int i = 0; i < aList.size();i++){
            if(SearchType.equalsIgnoreCase(aList.get(i).getDay())){
                 JOptionPane.showMessageDialog(null, "Subject Name: "+aList.get(i).getName()+"\n Day of Study: "+aList.get(i).getDay()+"\n Time to Start: "+aList.get(i).getStarttime()+"\n Time to Finish: "+aList.get(i).getFintime());
            }
            if(!SearchType.equalsIgnoreCase(aList.get(i).getDay())){
                JOptionPane.showMessageDialog(null,"Entry not found");
            }
        }
            
    }//GEN-LAST:event_btnSearchActionPerformed

    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        name = Nametf.getText();
        day = Studytf.getText();
        starttime = Integer.parseInt(Starttf.getText());
        fintime = Integer.parseInt(Finishtf.getText());
        
        //create a new Assessment object
        StudyPlan a = new StudyPlan();
        
        //add contents of textfields to q
        a.setName(name);
        a.setDay(day);
        a.setStarttime(starttime);
        a.setFintime(fintime);
        
        //add q to array of Assessment objects
        aList.add(a);
        //increase count to show that another object has been added to the array
        count++;
        
        Nametf.setText("");
        Studytf.setText("");
        Starttf.setText("");
        Finishtf.setText("");
        
        writeObjectToFile();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String question = JOptionPane.showInputDialog(null, "Delete File?");

        File f = new File("data.txt");

        if (f.exists()) {
            f.delete();
            JOptionPane.showMessageDialog(null, "File Gone");
        }

        for (int i = 0; i < aList.size(); i++) {
            aList.remove(i);
        }
    

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new JCStudy().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyPlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyPlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyPlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyPlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudyPlanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Finishtf;
    private javax.swing.JTextField Nametf;
    private javax.swing.JTextField Starttf;
    private javax.swing.JTextField Studytf;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblEx1;
    private javax.swing.JLabel lblEx2;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTimeFin;
    private javax.swing.JLabel lblTimeStart;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
